# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-06 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20190105_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='public_read',
            new_name='public_readable',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='public_write',
            new_name='public_writable',
        ),
    ]
