REPORT ZMATH.

DATA: A TYPE I VALUE 115,
      B TYPE I VALUE 119.
      IF A LT B.
      WRITE: / 'A is less than B'.
      ENDIF.

DATA: A TYPE I.
      IF A IS INITIAL.
      WRITE: / 'A is initial'.
      ELSEIF A EQ 3.
      WRITE: / 'A... it''s three!'.
      ELSE.
      WRITE: / 'A is some other thing'.
      ENDIF.

*DATA: P(10) TYPE C VALUE 'APPLE',
*      Q(10) TYPE C VALUE 'CHAIR'.
*      IF P CA Q.
*      WRITE: / 'P contains at least one character of Q'.
*      ENDIF.

